// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp1.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Skupina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skupiny");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazev = "swi1"
                        },
                        new
                        {
                            Id = 2,
                            Nazev = "swi2"
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prijmeni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SkupinaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SkupinaId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jmeno = "Andrea",
                            Prijmeni = "Nova",
                            SkupinaId = 1
                        },
                        new
                        {
                            Id = 2,
                            Jmeno = "Jiri",
                            Prijmeni = "Novotny",
                            SkupinaId = 2
                        },
                        new
                        {
                            Id = 3,
                            Jmeno = "Karel",
                            Prijmeni = "Vesely",
                            SkupinaId = 2
                        });
                });

            modelBuilder.Entity("Student", b =>
                {
                    b.HasOne("Skupina", "Skupina")
                        .WithMany("Studenti")
                        .HasForeignKey("SkupinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skupina");
                });

            modelBuilder.Entity("Skupina", b =>
                {
                    b.Navigation("Studenti");
                });
#pragma warning restore 612, 618
        }
    }
}
