// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utb.PizzaKiosk.Models;

#nullable disable

namespace Utb.PizzaKiosk.Models.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Utb.PizzaKiosk.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Jmeno")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "s ananasem",
                            Jmeno = "Hawai",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "se syrem",
                            Jmeno = "Syrova",
                            Price = 130.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "se sunkou",
                            Jmeno = "Sunkova",
                            Price = 140.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
