<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" Version="13.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UTB.ConcurrencyTest.ServiceDefaults\UTB.ConcurrencyTest.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
