// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utb;

#nullable disable

namespace Utb.EntityFramework.Students.Migrations
{
    [DbContext(typeof(SkolaContext))]
    [Migration("20230915101411_PrvniMigrace")]
    partial class PrvniMigrace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("Utb.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Studenti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jolana",
                            Points = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Karel",
                            Points = 7.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pavel",
                            Points = 55.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
