// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Utb.PizzaKiosk.Models;

#nullable disable

namespace Utb.PizzaKiosk.Models.Migrations
{
    [DbContext(typeof(PizzaKioskContext))]
    [Migration("20230906143122_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Utb.PizzaKiosk.Models.PizzaConfigurationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PizzaOptions");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PizzaConfigurationOption");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Utb.PizzaKiosk.Models.StringOptions", b =>
                {
                    b.HasBaseType("Utb.PizzaKiosk.Models.PizzaConfigurationOption");

                    b.Property<int>("DefaultValueIndex")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("StringOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pizza size",
                            DefaultValueIndex = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
