@Students.WebAPI_HostAddress = https://localhost:7042

POST {{Students.WebAPI_HostAddress}}/Seed

###

GET {{Students.WebAPI_HostAddress}}/Students/

###

GET {{Students.WebAPI_HostAddress}}/Students/Active

###

GET {{Students.WebAPI_HostAddress}}/students/1

###

POST {{Students.WebAPI_HostAddress}}/Students
Content-Type: application/json

{
  "studentId": 0,
  "jmeno": "Lenka",
  "studuje": true
}

###

PUT {{Students.WebAPI_HostAddress}}/students/1
Content-Type: application/json

{
  "studentId": 1,
  "jmeno": "Novotna",
  "studuje": true
}
###

DELETE {{Students.WebAPI_HostAddress}}/students/1

###

GET {{Students.WebAPI_HostAddress}}/openapi/v1.json

###
