@Knihovna.WebAPI_HostAddress = https://localhost:7219

POST {{Knihovna.WebAPI_HostAddress}}/Seed

###

GET {{Knihovna.WebAPI_HostAddress}}/books

###

GET {{Knihovna.WebAPI_HostAddress}}/books/1

###

POST {{Knihovna.WebAPI_HostAddress}}/books
Content-Type: application/json

{
  "knihaId": 0,
  "nazev": "Vojna a mir"
}

###

PUT {{Knihovna.WebAPI_HostAddress}}/books/1
Content-Type: application/json

{
  "knihaId": 0,
  "nazev": "Zlocin a trest"
}

###

DELETE {{Knihovna.WebAPI_HostAddress}}/books/1

###
