@UTB.School.WebApi_HostAddress = https://localhost:7194


POST {{UTB.School.WebApi_HostAddress}}/dev/seed

###

GET {{UTB.School.WebApi_HostAddress}}/students

###

GET {{UTB.School.WebApi_HostAddress}}/students?isActive=true

###

GET {{UTB.School.WebApi_HostAddress}}/students?isActive=false

###



POST {{UTB.School.WebApi_HostAddress}}/students

###
